# Generated by Django 6.0.4 on 2026-06-26 12:37

import django.db.models.deletion
import django_choices_field.fields
import kanne_server.fields
import simple_history.models
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAnalogSignal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the signal', max_length=1000)),
                ('t_start', kanne_server.fields.QuantityField(base_unit='picosecond', default=0, help_text='The start time of the signal, stored in picoseconds')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('sampling_rate', kanne_server.fields.QuantityField(base_unit='nanohertz', default=1000000000000, help_text='The sampling frequency of the signal, stored in nanohertz')),
                ('unit', models.CharField(blank=True, default='mV', help_text='The unit of the signal', max_length=100, null=True)),
                ('color', models.CharField(default='#000000', help_text='The color of the signal in HEX', max_length=7)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical analog signal',
                'verbose_name_plural': 'historical analog signals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBlock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the recording session', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('recording_time', models.DateTimeField(blank=True, help_text='The time the recording session was acquired', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical block',
                'verbose_name_plural': 'historical blocks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBlockSegment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_time', kanne_server.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The start time of the segment, stored in picoseconds', null=True)),
                ('end_time', kanne_server.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The end time of the segment, stored in picoseconds', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical block segment',
                'verbose_name_plural': 'historical block segments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDataset',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The time the dataset was created')),
                ('name', models.CharField(help_text='The name of the dataset', max_length=200)),
                ('description', models.CharField(blank=True, help_text='The description of the dataset', max_length=1000, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether the dataset is the current default dataset for the user')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical dataset',
                'verbose_name_plural': 'historical datasets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalExperiment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the experiment', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical experiment',
                'verbose_name_plural': 'historical experiments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalInstrument',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('manufacturer', models.CharField(blank=True, max_length=1000, null=True)),
                ('model', models.CharField(blank=True, max_length=1000, null=True)),
                ('serial_number', models.CharField(db_index=True, max_length=1000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical instrument',
                'verbose_name_plural': 'historical instruments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIrregularlySampledSignal',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the signal', max_length=1000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical irregularly sampled signal',
                'verbose_name_plural': 'historical irregularly sampled signals',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNeuronModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, help_text='The hash of the model', max_length=1000)),
                ('json_model', models.JSONField(blank=True, default=dict, help_text='The json model of the neuron')),
                ('name', models.CharField(help_text='The name of the model', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical neuron model',
                'verbose_name_plural': 'historical neuron models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalROI',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='The label of the ROI', max_length=1000, null=True)),
                ('vectors', models.JSONField(default=list, help_text='A list of the ROI Vectors (specific for each type)', max_length=3000)),
                ('max_t', models.IntegerField(default=0, help_text='The maximum time of the ROI')),
                ('min_t', models.IntegerField(default=0, help_text='The minimum time of the ROI')),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('line', 'Line'), ('point', 'Point'), ('spike', 'Spike'), ('slice', 'Slice')], default='spike', help_text='The Roi can have vasrying kind, consult your API', max_length=5)),
                ('color', models.CharField(blank=True, help_text='The color of the ROI (for UI)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='The time the ROI was created')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical roi',
                'verbose_name_plural': 'historical rois',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSpikeTrain',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the signal', max_length=1000)),
                ('unit', models.CharField(blank=True, default='sec', help_text='The unit of the signal', max_length=100, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical spike train',
                'verbose_name_plural': 'historical spike trains',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTrace',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the image', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('TIME', 'Mask (Value represent Labels)'), ('VOLTAGE', 'Voltage (Value represent Intensity)'), ('CURRENT', 'Current (Value represent Intensity)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='The Representation can have vasrying kind, consult your API', max_length=7)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical trace',
                'verbose_name_plural': 'historical traces',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalViewCollection',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the view', max_length=1000)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical view collection',
                'verbose_name_plural': 'historical view collections',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('manufacturer', models.CharField(blank=True, max_length=1000, null=True)),
                ('model', models.CharField(blank=True, max_length=1000, null=True)),
                ('serial_number', models.CharField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IrregularlySampledSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the signal', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Mechanism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The mechanism that can be simulated with the mod environment', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('parameters', models.JSONField(default=list, help_text='The parameter ports of the mechanism, stored as a json object with the port name as key and the port type as value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the model collection', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModelWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the workspace', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the mod environment', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NeuronModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(help_text='The hash of the model', max_length=1000, unique=True)),
                ('json_model', models.JSONField(blank=True, default=dict, help_text='The json model of the neuron')),
                ('name', models.CharField(help_text='The name of the model', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('TIME', 'Mask (Value represent Labels)'), ('VOLTAGE', 'Voltage (Value represent Intensity)'), ('CURRENT', 'Current (Value represent Intensity)'), ('INA', 'INA (Value represent Intensity)')], default='VOLTAGE', help_text='The Representation can have vasrying kind, consult your API', max_length=7)),
                ('cell', models.CharField(help_text='The cell of the recording', max_length=1000)),
                ('location', models.CharField(help_text='The location of the recording', max_length=1000)),
                ('position', models.CharField(help_text='The position of the recording', max_length=1000)),
                ('label', models.CharField(help_text='The label of the recording', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='The label of the ROI', max_length=1000, null=True)),
                ('vectors', models.JSONField(default=list, help_text='A list of the ROI Vectors (specific for each type)', max_length=3000)),
                ('max_t', models.IntegerField(default=0, help_text='The maximum time of the ROI')),
                ('min_t', models.IntegerField(default=0, help_text='The minimum time of the ROI')),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('line', 'Line'), ('point', 'Point'), ('spike', 'Spike'), ('slice', 'Slice')], default='spike', help_text='The Roi can have vasrying kind, consult your API', max_length=5)),
                ('color', models.CharField(blank=True, help_text='The color of the ROI (for UI)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, help_text='The time the ROI was created')),
            ],
        ),
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', kanne_server.fields.QuantityField(base_unit='picosecond', help_text='The duration of the run, stored in picoseconds')),
                ('dt', kanne_server.fields.QuantityField(base_unit='picosecond', default=1000000000000, help_text='The time step of the run, stored in picoseconds')),
                ('name', models.CharField(help_text='The name of the run', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpikeTrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the signal', max_length=1000)),
                ('unit', models.CharField(blank=True, default='sec', help_text='The unit of the signal', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('CURRENT', 'Current (Value represent Intensity)'), ('VOLTAGE', 'Voltage (Value represent Intensity)')], default='CURRENT', help_text='The Representastion can have vasrying kind, consult your API', max_length=7)),
                ('cell', models.CharField(help_text='The cell thsat was ssrecorded', max_length=1000)),
                ('location', models.CharField(help_text='The location of the recording', max_length=1000)),
                ('position', models.CharField(help_text='The position of the recording', max_length=1000)),
                ('label', models.CharField(help_text='The label of the recording', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('a_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('is_global', models.BooleanField(default=False, help_text='Whether the view is global or not')),
                ('start_time', models.DateTimeField(blank=True, help_text='The start time of the view', null=True)),
                ('end_time', models.DateTimeField(blank=True, help_text='The end time of the view', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the image', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('kind', django_choices_field.fields.TextChoicesField(choices=[('TIME', 'Mask (Value represent Labels)'), ('VOLTAGE', 'Voltage (Value represent Intensity)'), ('CURRENT', 'Current (Value represent Intensity)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='The Representation can have vasrying kind, consult your API', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [('inspect_image', 'Can view image')],
            },
        ),
        migrations.CreateModel(
            name='ViewCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the view', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_group', models.CharField(help_text='The group of the workspace that the mapping belongs to (if its subdivided into groups)', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalogSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the signal', max_length=1000)),
                ('t_start', kanne_server.fields.QuantityField(base_unit='picosecond', default=0, help_text='The start time of the signal, stored in picoseconds')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('sampling_rate', kanne_server.fields.QuantityField(base_unit='nanohertz', default=1000000000000, help_text='The sampling frequency of the signal, stored in nanohertz')),
                ('unit', models.CharField(blank=True, default='mV', help_text='The unit of the signal', max_length=100, null=True)),
                ('color', models.CharField(default='#000000', help_text='The color of the signal in HEX', max_length=7)),
                ('pinned_by', models.ManyToManyField(blank=True, help_text='The users that pinned this segment', related_name='pinned_analog_signals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalogSignalChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='The index of the channel in the signal')),
                ('name', models.CharField(default='', help_text='The name of the channel', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('unit', models.CharField(blank=True, default='mV', help_text='The unit of the channel', max_length=100, null=True)),
                ('color', models.CharField(blank=True, help_text='The color of the signal in HEX', max_length=7, null=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.analogsignal')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the recording session', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recording_time', models.DateTimeField(blank=True, help_text='The time the recording session was acquired', null=True)),
                ('creator', models.ForeignKey(help_text='The user that created the recording session', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='authentikate.organization')),
                ('pinned_by', models.ManyToManyField(help_text='The users that have pinned the recording session', related_name='pinned_recording_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BlockGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='The label of the recording group', max_length=1000)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.block')),
            ],
        ),
        migrations.CreateModel(
            name='BlockSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', kanne_server.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The start time of the segment, stored in picoseconds', null=True)),
                ('end_time', kanne_server.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The end time of the segment, stored in picoseconds', null=True)),
                ('organization', models.ForeignKey(blank=True, help_text='The organization that owns the segment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_segments', to='authentikate.organization')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.block')),
            ],
        ),
        migrations.AddField(
            model_name='analogsignal',
            name='recording_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_signals', to='core.blocksegment'),
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time the dataset was created')),
                ('name', models.CharField(help_text='The name of the dataset', max_length=200)),
                ('description', models.CharField(blank=True, help_text='The description of the dataset', max_length=1000, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether the dataset is the current default dataset for the user')),
                ('creator', models.ForeignKey(help_text='The user that created the dataset', on_delete=django.db.models.deletion.CASCADE, related_name='created_datasets', to=settings.AUTH_USER_MODEL)),
                ('membership', models.ForeignKey(help_text='The organization that owns the dataset', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='authentikate.membership')),
                ('organization', models.ForeignKey(help_text='The organization that owns the dataset', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='authentikate.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.dataset')),
                ('pinned_by', models.ManyToManyField(blank=True, help_text='The users that have pinned the dataset', related_name='pinned_datasets', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='Tags for the dataset', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='dataset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.dataset'),
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the experiment', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(help_text='The user that created the experimesnt', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pinned_by', models.ManyToManyField(help_text='The users that have pinned the experiment', related_name='pinned_experiments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentRecordingView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', kanne_server.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The offset of the view, stored in picoseconds', null=True)),
                ('duration', kanne_server.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The duration of the view, stored in picoseconds', null=True)),
                ('label', models.CharField(blank=True, help_text='The label of the view', max_length=1000, null=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recording_views', to='core.experiment')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization that owns the recording view', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_recording_views', to='authentikate.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentStimulusView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', kanne_server.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The offset of the view, stored in picoseconds', null=True)),
                ('duration', kanne_server.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The duration of the view, stored in picoseconds', null=True)),
                ('label', models.CharField(blank=True, help_text='The label of the view', max_length=1000, null=True)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stimulus_views', to='core.experiment')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization that owns the stimulus view', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_stimulus_views', to='authentikate.organization')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the file', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.dataset')),
                ('organization', models.ForeignKey(blank=True, help_text='The organization that owns the file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='authentikate.organization')),
                ('origins', models.ManyToManyField(related_name='derived', to='core.file')),
            ],
        ),
    ]
