# Generated by Django 6.0.4 on 2026-04-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanismmapping',
            name='name',
            field=models.CharField(default='cad', help_text='The name of the mapping', max_length=1000),
            preserve_default=False,
        ),
    ]
