# Generated by Django 6.0.4 on 2026-09-18 11:50

import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        # Renamed, not dropped: the events layer's pickers are the table pickers now, shared with
        # the series and point layers, and a remove + add would lose every stored entry.
        migrations.RenameField(model_name='experimentlayer', old_name='event_color_bys', new_name='table_color_bys'),
        migrations.RenameField(model_name='experimentlayer', old_name='event_filter_bys', new_name='table_filter_bys'),
        migrations.RenameField(model_name='historicalexperimentlayer', old_name='event_color_bys', new_name='table_color_bys'),
        migrations.RenameField(model_name='historicalexperimentlayer', old_name='event_filter_bys', new_name='table_filter_bys'),
        migrations.RemoveConstraint(
            model_name='experimentlayer',
            name='experiment_layer_has_the_source_its_kind_names',
        ),
        migrations.AddField(
            model_name='experimentlayer',
            name='gamma',
            field=models.FloatField(blank=True, help_text='(heatmap) The gamma the colour range is drawn through; null is linear', null=True),
        ),
        migrations.AddField(
            model_name='experimentlayer',
            name='interpolation',
            field=django_choices_field.fields.TextChoicesField(choices=[('linear', 'Linear (a straight line between consecutive rows)'), ('step', 'Step (each value holds until the next row)'), ('points', 'Points (a marker per row, unjoined)')], default='linear', help_text='(series) How consecutive rows are joined', max_length=6),
        ),
        migrations.AddField(
            model_name='experimentlayer',
            name='point_size',
            field=models.FloatField(blank=True, help_text="(point) A point's size, in screen pixels", null=True),
        ),
        migrations.AddField(
            model_name='experimentlayer',
            name='row_axis',
            field=models.CharField(blank=True, help_text='(heatmap) The lens axis drawn down the image; null resolves to its FREQUENCY axis, else CHANNEL, else INDEX', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experimentlayer',
            name='size_column',
            field=models.CharField(blank=True, help_text="(point) A numeric column scaling each point's size", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experimentlayer',
            name='unit_axis',
            field=models.CharField(blank=True, help_text='(waveform) The lens axis enumerating the units; null resolves to its INDEX axis', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='experimentlayer',
            name='value_column',
            field=models.CharField(blank=True, help_text="(series) The numeric column drawn as the line's value", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalexperimentlayer',
            name='gamma',
            field=models.FloatField(blank=True, help_text='(heatmap) The gamma the colour range is drawn through; null is linear', null=True),
        ),
        migrations.AddField(
            model_name='historicalexperimentlayer',
            name='interpolation',
            field=django_choices_field.fields.TextChoicesField(choices=[('linear', 'Linear (a straight line between consecutive rows)'), ('step', 'Step (each value holds until the next row)'), ('points', 'Points (a marker per row, unjoined)')], default='linear', help_text='(series) How consecutive rows are joined', max_length=6),
        ),
        migrations.AddField(
            model_name='historicalexperimentlayer',
            name='point_size',
            field=models.FloatField(blank=True, help_text="(point) A point's size, in screen pixels", null=True),
        ),
        migrations.AddField(
            model_name='historicalexperimentlayer',
            name='row_axis',
            field=models.CharField(blank=True, help_text='(heatmap) The lens axis drawn down the image; null resolves to its FREQUENCY axis, else CHANNEL, else INDEX', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalexperimentlayer',
            name='size_column',
            field=models.CharField(blank=True, help_text="(point) A numeric column scaling each point's size", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalexperimentlayer',
            name='unit_axis',
            field=models.CharField(blank=True, help_text='(waveform) The lens axis enumerating the units; null resolves to its INDEX axis', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalexperimentlayer',
            name='value_column',
            field=models.CharField(blank=True, help_text="(series) The numeric column drawn as the line's value", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experimentlayer',
            name='kind',
            field=django_choices_field.fields.TextChoicesField(choices=[('trace', 'Trace (a lens over an array dataset, drawn as a line per channel)'), ('spikes', 'Spikes (a sparse raster, drawn as a tick per nonzero, a row per unit)'), ('events', 'Events (a table with a TIME column, drawn as marks or intervals)'), ('annotation', "Annotation (an annotation collection's hand-drawn marks)"), ('heatmap', 'Heatmap (a lens over an array dataset, drawn as an image: time across, one other axis down)'), ('series', 'Series (a numeric column of a table with a TIME column, drawn as a line)'), ('waveform', 'Waveform (a lens over per-unit templates, drawn in peri-spike time)'), ('point', 'Point (a table with SPACE coordinate columns, drawn as a point per row)')], help_text='How this layer draws its data, and so which source it has', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalexperimentlayer',
            name='kind',
            field=django_choices_field.fields.TextChoicesField(choices=[('trace', 'Trace (a lens over an array dataset, drawn as a line per channel)'), ('spikes', 'Spikes (a sparse raster, drawn as a tick per nonzero, a row per unit)'), ('events', 'Events (a table with a TIME column, drawn as marks or intervals)'), ('annotation', "Annotation (an annotation collection's hand-drawn marks)"), ('heatmap', 'Heatmap (a lens over an array dataset, drawn as an image: time across, one other axis down)'), ('series', 'Series (a numeric column of a table with a TIME column, drawn as a line)'), ('waveform', 'Waveform (a lens over per-unit templates, drawn in peri-spike time)'), ('point', 'Point (a table with SPACE coordinate columns, drawn as a point per row)')], help_text='How this layer draws its data, and so which source it has', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='experimentlayer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('annotation_collection__isnull', True), ('kind__in', ['trace', 'heatmap', 'waveform']), ('lens__isnull', False), ('sparse_dataset__isnull', True), ('table_dataset__isnull', True)), models.Q(('annotation_collection__isnull', True), ('kind', 'spikes'), ('lens__isnull', True), ('sparse_dataset__isnull', False), ('table_dataset__isnull', True)), models.Q(('annotation_collection__isnull', True), ('kind__in', ['events', 'series', 'point']), ('lens__isnull', True), ('sparse_dataset__isnull', True), ('table_dataset__isnull', False)), models.Q(('annotation_collection__isnull', False), ('kind', 'annotation'), ('lens__isnull', True), ('sparse_dataset__isnull', True), ('table_dataset__isnull', True)), _connector='OR'), name='experiment_layer_has_the_source_its_kind_names'),
        ),
        migrations.AlterField(
            model_name='experimentlayer',
            name='table_color_bys',
            field=models.JSONField(blank=True, default=list, help_text='(events, series, point) The colour pickers over the table and what it references; which one is active is `active_color_by`'),
        ),
        migrations.AlterField(
            model_name='experimentlayer',
            name='table_filter_bys',
            field=models.JSONField(blank=True, default=list, help_text='(events, series, point) The filter pickers over the table and what it references; which apply is `active_filter_bys`'),
        ),
        migrations.AlterField(
            model_name='historicalexperimentlayer',
            name='table_color_bys',
            field=models.JSONField(blank=True, default=list, help_text='(events, series, point) The colour pickers over the table and what it references; which one is active is `active_color_by`'),
        ),
        migrations.AlterField(
            model_name='historicalexperimentlayer',
            name='table_filter_bys',
            field=models.JSONField(blank=True, default=list, help_text='(events, series, point) The filter pickers over the table and what it references; which apply is `active_filter_bys`'),
        ),
    ]
