# Generated by Django 4.2.8 on 2025-04-23 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="neuronmodel",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent model of the neuron",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="core.neuronmodel",
            ),
        ),
    ]
