# Generated by Django 6.0.4 on 2026-06-26 12:37

import django.db.models.deletion
import simple_history.models
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('core', '0001_initial'),
        ('datalayer', '0001_initial'),
        ('koherent', '0003_rename_assignation_to_task'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='store',
            field=models.ForeignKey(blank=True, help_text='The store of the file', null=True, on_delete=django.db.models.deletion.CASCADE, to='datalayer.bigfilestore'),
        ),
        migrations.AddField(
            model_name='block',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.file'),
        ),
        migrations.AddField(
            model_name='historicalanalogsignal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalanalogsignal',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.analogsignal'),
        ),
        migrations.AddField(
            model_name='historicalanalogsignal',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalanalogsignal',
            name='recording_segment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.blocksegment'),
        ),
        migrations.AddField(
            model_name='historicalanalogsignal',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalblock',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalblock',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created the recording session', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalblock',
            name='dataset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.dataset'),
        ),
        migrations.AddField(
            model_name='historicalblock',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.block'),
        ),
        migrations.AddField(
            model_name='historicalblock',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalblock',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalblock',
            name='origin',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.file'),
        ),
        migrations.AddField(
            model_name='historicalblock',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalblocksegment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalblocksegment',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.blocksegment'),
        ),
        migrations.AddField(
            model_name='historicalblocksegment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalblocksegment',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization that owns the segment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalblocksegment',
            name='session',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.block'),
        ),
        migrations.AddField(
            model_name='historicalblocksegment',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created the dataset', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.dataset'),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='membership',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization that owns the dataset', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.membership'),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization that owns the dataset', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.dataset'),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalexperiment',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalexperiment',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created the experimesnt', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexperiment',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.experiment'),
        ),
        migrations.AddField(
            model_name='historicalexperiment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalexperiment',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalinstrument',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalinstrument',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalinstrument',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalirregularlysampledsignal',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalirregularlysampledsignal',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalirregularlysampledsignal',
            name='recording_segment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.blocksegment'),
        ),
        migrations.AddField(
            model_name='historicalirregularlysampledsignal',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalneuronmodel',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalneuronmodel',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created the model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalneuronmodel',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalneuronmodel',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalroi',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalroi',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created the ROI', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalroi',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalroi',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalspiketrain',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalspiketrain',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalspiketrain',
            name='recording_segment',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.blocksegment'),
        ),
        migrations.AddField(
            model_name='historicalspiketrain',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaltrace',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicaltrace',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltrace',
            name='dataset',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The dataset that the trace belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.dataset'),
        ),
        migrations.AddField(
            model_name='historicaltrace',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaltrace',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization that owns the dataset', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicaltrace',
            name='store',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The store of the trace', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datalayer.zarrstore'),
        ),
        migrations.AddField(
            model_name='historicaltrace',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalviewcollection',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalviewcollection',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalviewcollection',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization that owns the view collection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalviewcollection',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalinstrument',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.instrument'),
        ),
        migrations.AddField(
            model_name='irregularlysampledsignal',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that pinned this segment', related_name='pinned_irregularly_sampled_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='irregularlysampledsignal',
            name='recording_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irregularly_sampled_signals', to='core.blocksegment'),
        ),
        migrations.AddField(
            model_name='historicalirregularlysampledsignal',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.irregularlysampledsignal'),
        ),
        migrations.AddField(
            model_name='modelcollection',
            name='creator',
            field=models.ForeignKey(help_text='The user that created the model collection', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelcollection',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that owns the model collection', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_collections', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='modelcollection',
            name='pinned_by',
            field=models.ManyToManyField(help_text='The users that have pinned the model collection', related_name='pinned_model_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelworkspace',
            name='creator',
            field=models.ForeignKey(help_text='The user that created the workspace', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelworkspace',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that owns the workspace', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_workspaces', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='modelworkspace',
            name='pinned_by',
            field=models.ManyToManyField(help_text='The users that have pinned the workspace', related_name='pinned_workspaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modenvironment',
            name='organization',
            field=models.ForeignKey(help_text='The organization that owns the mod environment', on_delete=django.db.models.deletion.CASCADE, related_name='mod_environments', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='modenvironment',
            name='store',
            field=models.ForeignKey(blank=True, help_text='The .mod file, stored in S3', null=True, on_delete=django.db.models.deletion.CASCADE, to='datalayer.bigfilestore'),
        ),
        migrations.AddField(
            model_name='mechanism',
            name='environment',
            field=models.ForeignKey(help_text='The mod environment that the mechanism sbelongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mechanisms', to='core.modenvironment'),
        ),
        migrations.AddField(
            model_name='historicalneuronmodel',
            name='environment',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The mod environment that the neuron model belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.modenvironment'),
        ),
        migrations.AddField(
            model_name='neuronmodel',
            name='creator',
            field=models.ForeignKey(help_text='The user that created the model', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='neuronmodel',
            name='environment',
            field=models.ForeignKey(help_text='The mod environment that the neuron model belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.modenvironment'),
        ),
        migrations.AddField(
            model_name='neuronmodel',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent model of the neuron (if it was derived from another model)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.neuronmodel'),
        ),
        migrations.AddField(
            model_name='neuronmodel',
            name='pinned_by',
            field=models.ManyToManyField(help_text='The users that have pinned the model', related_name='pinned_models', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modelcollection',
            name='comparison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comparing_collections', to='core.neuronmodel'),
        ),
        migrations.AddField(
            model_name='modelcollection',
            name='models',
            field=models.ManyToManyField(help_text='The models that are in the collection', related_name='model_collections', to='core.neuronmodel'),
        ),
        migrations.AddField(
            model_name='historicalneuronmodel',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.neuronmodel'),
        ),
        migrations.AddField(
            model_name='historicalneuronmodel',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The parent model of the neuron (if it was derived from another model)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.neuronmodel'),
        ),
        migrations.AddField(
            model_name='experimentrecordingview',
            name='recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_views', to='core.recording'),
        ),
        migrations.AddField(
            model_name='roi',
            name='creator',
            field=models.ForeignKey(help_text='The user that created the ROI', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='roi',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that pinned this ROI', related_name='pinned_rois', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalroi',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.roi'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='creator',
            field=models.ForeignKey(help_text='The user that created the run', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='simulation',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='core.neuronmodel'),
        ),
        migrations.AddField(
            model_name='recording',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='core.simulation'),
        ),
        migrations.AddField(
            model_name='spiketrain',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that pinned this segment', related_name='pinned_spike_trains', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spiketrain',
            name='recording_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spike_trains', to='core.blocksegment'),
        ),
        migrations.AddField(
            model_name='historicalspiketrain',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.spiketrain'),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimuli', to='core.simulation'),
        ),
        migrations.AddField(
            model_name='experimentstimulusview',
            name='stimulus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_views', to='core.stimulus'),
        ),
        migrations.AddField(
            model_name='trace',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trace',
            name='dataset',
            field=models.ForeignKey(blank=True, help_text='The dataset that the trace belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='core.dataset'),
        ),
        migrations.AddField(
            model_name='trace',
            name='organization',
            field=models.ForeignKey(help_text='The organization that owns the dataset', on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='trace',
            name='pinned_by',
            field=models.ManyToManyField(help_text='The users that have pinned the images', related_name='pinned_traces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trace',
            name='store',
            field=models.ForeignKey(blank=True, help_text='The store of the trace', null=True, on_delete=django.db.models.deletion.CASCADE, to='datalayer.zarrstore'),
        ),
        migrations.AddField(
            model_name='trace',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='timelineview',
            name='trace',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trace'),
        ),
        migrations.AddField(
            model_name='stimulus',
            name='trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stimuli', to='core.trace'),
        ),
        migrations.AddField(
            model_name='spiketrain',
            name='trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spike_trains', to='core.trace'),
        ),
        migrations.AddField(
            model_name='simulation',
            name='time_trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='core.trace'),
        ),
        migrations.AddField(
            model_name='roi',
            name='trace',
            field=models.ForeignKey(help_text='The Representation this ROI was original used to create (drawn on)', on_delete=django.db.models.deletion.CASCADE, related_name='rois', to='core.trace'),
        ),
        migrations.AddField(
            model_name='recording',
            name='trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='core.trace'),
        ),
        migrations.AddField(
            model_name='irregularlysampledsignal',
            name='time_trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irregularly_sampled_time_signals', to='core.trace'),
        ),
        migrations.AddField(
            model_name='irregularlysampledsignal',
            name='trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irregularly_sampled_trace_signals', to='core.trace'),
        ),
        migrations.AddField(
            model_name='historicaltrace',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.trace'),
        ),
        migrations.AddField(
            model_name='historicalspiketrain',
            name='trace',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.trace'),
        ),
        migrations.AddField(
            model_name='historicalroi',
            name='trace',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The Representation this ROI was original used to create (drawn on)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.trace'),
        ),
        migrations.AddField(
            model_name='historicalirregularlysampledsignal',
            name='time_trace',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.trace'),
        ),
        migrations.AddField(
            model_name='historicalirregularlysampledsignal',
            name='trace',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.trace'),
        ),
        migrations.AddField(
            model_name='historicalexperiment',
            name='time_trace',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.trace'),
        ),
        migrations.AddField(
            model_name='historicalanalogsignal',
            name='time_trace',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.trace'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='time_trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='core.trace'),
        ),
        migrations.AddField(
            model_name='analogsignalchannel',
            name='trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_signal_channels', to='core.trace'),
        ),
        migrations.AddField(
            model_name='analogsignal',
            name='time_trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_signal_time_traces', to='core.trace'),
        ),
        migrations.AddField(
            model_name='viewcollection',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that owns the view collection', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_collections', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='timelineview',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.viewcollection'),
        ),
        migrations.AddField(
            model_name='historicalviewcollection',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.viewcollection'),
        ),
        migrations.AddField(
            model_name='workspacemapping',
            name='model',
            field=models.ForeignKey(help_text='The neuron model that the mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.neuronmodel'),
        ),
        migrations.AddField(
            model_name='workspacemapping',
            name='workspace',
            field=models.ForeignKey(help_text='The workspace that the mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.modelworkspace'),
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('creator', 'is_default'), name='unique_default_per_creator'),
        ),
    ]
