# Generated by Django 6.0.4 on 2026-04-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mechanismmapping_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanismmapping',
            name='cell_id',
            field=models.CharField(default=1, help_text='The id of the cell that the mechanism is mapped to', max_length=1000),
            preserve_default=False,
        ),
    ]
