# Generated by Django 5.2 on 2025-09-26 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dataset_membership_historicaldataset_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='acquired_at',
            new_name='recording_time',
        ),
        migrations.RenameField(
            model_name='historicalblock',
            old_name='acquired_at',
            new_name='recording_time',
        ),
    ]
