# Generated by Django 6.0.4 on 2026-06-30 16:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0006_alter_app_identifier_alter_release_unique_together'),
        ('core', '0002_initial'),
        ('datalayer', '0001_initial'),
        ('koherent', '0003_rename_assignation_to_task'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('a_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('is_global', models.BooleanField(default=False, help_text='Whether the view is global or not')),
                ('series_identifier', models.CharField(blank=True, help_text='The series identifier of the file', max_length=1000, null=True)),
            ],
            options={
                'default_related_name': 'file_views',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFile',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='The name of the file', max_length=1000)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('size', models.BigIntegerField(blank=True, help_text='The size of the file in bytes', null=True)),
                ('content_type', models.CharField(blank=True, help_text='The content type of the file', max_length=1000, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical file',
                'verbose_name_plural': 'historical files',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFileView',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('a_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('a_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('t_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_min', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('c_max', models.IntegerField(blank=True, help_text='The index of the channel', null=True)),
                ('is_global', models.BooleanField(default=False, help_text='Whether the view is global or not')),
                ('series_identifier', models.CharField(blank=True, help_text='The series identifier of the file', max_length=1000, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical file view',
                'verbose_name_plural': 'historical file views',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='dataset',
            name='unique_default_per_creator',
        ),
        migrations.AddField(
            model_name='dataset',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.CharField(blank=True, help_text='The content type of the file', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='created_through',
            field=models.ForeignKey(blank=True, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)ss', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='file',
            name='created_through_by',
            field=models.ForeignKey(blank=True, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='file',
            name='membership',
            field=models.ForeignKey(blank=True, help_text='The membership of the user that created the file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='authentikate.membership'),
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(blank=True, help_text='The size of the file in bytes', null=True),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('creator', 'is_default', 'organization'), name='unique_default_per_creator'),
        ),
        migrations.AddConstraint(
            model_name='dataset',
            constraint=models.UniqueConstraint(fields=('parent', 'name'), name='only_one_dataset_per_parent_and_name'),
        ),
        migrations.AddField(
            model_name='fileview',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.viewcollection'),
        ),
        migrations.AddField(
            model_name='fileview',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='core.file'),
        ),
        migrations.AddField(
            model_name='fileview',
            name='trace',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trace'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='created_through',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The task this object was created through, if any', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='created_through_by',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The assigner of the creating task, denormalized for fast filtering', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='dataset',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.dataset'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.file'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='membership',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The membership of the user that created the file', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.membership'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization that owns the file', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='store',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The store of the file', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='datalayer.bigfilestore'),
        ),
        migrations.AddField(
            model_name='historicalfile',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalfileview',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client'),
        ),
        migrations.AddField(
            model_name='historicalfileview',
            name='collection',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.viewcollection'),
        ),
        migrations.AddField(
            model_name='historicalfileview',
            name='file',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.file'),
        ),
        migrations.AddField(
            model_name='historicalfileview',
            name='history_relation',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.fileview'),
        ),
        migrations.AddField(
            model_name='historicalfileview',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalfileview',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalfileview',
            name='trace',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.trace'),
        ),
    ]
