# Generated by Django 6.0.4 on 2026-09-19 09:38

import django.db.models.deletion
import kanne_server.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sites_are_part_of_a_neuron_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='clock',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='simulation',
            name='model',
        ),
        migrations.CreateModel(
            name='SimulationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', kanne_server.fields.QuantityField(base_unit='picosecond', help_text="How long the model was run for (NEURON's tstop), stored in picoseconds")),
                ('dt', kanne_server.fields.QuantityField(base_unit='picosecond', blank=True, help_text="The integration time step (NEURON's dt), stored in picoseconds. Not the sampling period", null=True)),
                ('anchor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation', to='core.coordinateanchor')),
                ('model', models.ForeignKey(help_text='The neuron model that was integrated to compute these values', on_delete=django.db.models.deletion.CASCADE, related_name='simulation_states', to='core.neuronmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='HistoricalSimulation',
        ),
        migrations.DeleteModel(
            name='Simulation',
        ),
    ]
