# Generated by Django 5.2 on 2025-09-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_acquired_at_block_recording_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogsignal',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='analogsignal',
            name='t_start',
            field=models.FloatField(default=0.0, help_text='The start time of the signal in seconds'),
        ),
        migrations.AddField(
            model_name='historicalanalogsignal',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='historicalanalogsignal',
            name='t_start',
            field=models.FloatField(default=0.0, help_text='The start time of the signal in seconds'),
        ),
    ]
