# Generated by Django 6.0.4 on 2026-04-29 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('core', '0003_mechanismmapping_cell_id'),
        ('datalayer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanism',
            name='store',
        ),
        migrations.AlterField(
            model_name='mechanism',
            name='name',
            field=models.CharField(help_text='The mechanism that can be simulated with the mod environment', max_length=1000),
        ),
        migrations.AlterField(
            model_name='mechanismmapping',
            name='mechanism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.mechanism'),
        ),
        migrations.AlterField(
            model_name='mechanismmapping',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.neuronmodel'),
        ),
        migrations.CreateModel(
            name='ModEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the mod environment', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(help_text='The organization that owns the mod environment', on_delete=django.db.models.deletion.CASCADE, related_name='mod_environments', to='authentikate.organization')),
                ('store', models.ForeignKey(blank=True, help_text='The .mod file, stored in S3', null=True, on_delete=django.db.models.deletion.CASCADE, to='datalayer.bigfilestore')),
            ],
        ),
        migrations.AddField(
            model_name='mechanism',
            name='environment',
            field=models.ForeignKey(blank=True, help_text='The mod environment that the mechanism belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modenvironment'),
        ),
        migrations.AddField(
            model_name='neuronmodel',
            name='environment',
            field=models.ForeignKey(blank=True, help_text='The mod environment that the neuron model belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modenvironment'),
        ),
    ]
