# Generated by Django 4.2.8 on 2025-04-24 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_remove_experiment_simulations_experimentview"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the model collection", max_length=1000
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "creator",
                    models.ForeignKey(
                        help_text="The user that created the model collection",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pinned_by",
                    models.ManyToManyField(
                        help_text="The users that have pinned the model collection",
                        related_name="pinned_model_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="neuronmodel",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                help_text="The collection of the model",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="models",
                to="core.modelcollection",
            ),
        ),
    ]
