# Generated by Django 5.2 on 2025-09-26 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_analogsignal_description_analogsignal_t_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogsignal',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that pinned this segment', related_name='pinned_analog_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_signals', to='core.trace'),
        ),
        migrations.AlterField(
            model_name='blockgroup',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.block'),
        ),
        migrations.AlterField(
            model_name='blocksegment',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='core.block'),
        ),
        migrations.AlterField(
            model_name='irregularlysampledsignal',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, help_text='The users that pinned this segment', related_name='pinned_irregularly_sampled_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='irregularlysampledsignal',
            name='recording_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irregularly_sampled_signals', to='core.blocksegment'),
        ),
        migrations.AlterField(
            model_name='irregularlysampledsignal',
            name='time_trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irregularly_sampled_time_signals', to='core.trace'),
        ),
        migrations.AlterField(
            model_name='irregularlysampledsignal',
            name='trace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='irregularly_sampled_trace_signals', to='core.trace'),
        ),
    ]
