# Generated by Django 6.0.4 on 2026-04-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_mechanism_store_alter_mechanism_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MechanismMapping',
        ),
    ]
