# Generated by Django 4.2.8 on 2025-04-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_modelcollection_neuronmodel_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelcollection",
            name="comparison",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comparing_collections",
                to="core.neuronmodel",
            ),
        ),
    ]
