# Generated by Django 6.0.4 on 2026-04-29 08:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_mechanismmapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanism',
            name='organization',
        ),
        migrations.AlterField(
            model_name='experiment',
            name='creator',
            field=models.ForeignKey(help_text='The user that created the experimesnt', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalexperiment',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created the experimesnt', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mechanism',
            name='environment',
            field=models.ForeignKey(blank=True, help_text='The mod environment that the mechanism sbelongs to', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.modenvironment'),
        ),
    ]
