# Generated by Django 5.2 on 2025-09-26 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_analogsignal_pinned_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analogsignal',
            name='trace',
        ),
        migrations.RemoveField(
            model_name='historicalanalogsignal',
            name='trace',
        ),
        migrations.CreateModel(
            name='AnalogSignalChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(help_text='The index of the channel in the signal')),
                ('name', models.CharField(default='', help_text='The name of the channel', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('unit', models.CharField(blank=True, default='mV', help_text='The unit of the channel', max_length=100, null=True)),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='core.analogsignal')),
                ('trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_signal_channels', to='core.trace')),
            ],
        ),
    ]
