# Generated by Django 4.2.8 on 2025-04-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_modelcollection_comparison"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="neuronmodel",
            name="collection",
        ),
        migrations.AddField(
            model_name="modelcollection",
            name="models",
            field=models.ManyToManyField(
                help_text="The models that are in the collection",
                related_name="model_collections",
                to="core.neuronmodel",
            ),
        ),
    ]
