# Generated by Django 6.0.4 on 2026-04-29 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_mechanism_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanism',
            name='environment',
            field=models.ForeignKey(default=1, help_text='The mod environment that the mechanism sbelongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mechanisms', to='core.modenvironment'),
            preserve_default=False,
        ),
    ]
