# Generated by Django 5.2 on 2025-09-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_analogsignal_trace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogsignal',
            name='color',
            field=models.CharField(default='#000000', help_text='The color of the signal in HEX', max_length=7),
        ),
        migrations.AddField(
            model_name='analogsignalchannel',
            name='color',
            field=models.CharField(default='#000000', help_text='The color of the signal in HEX', max_length=7),
        ),
        migrations.AddField(
            model_name='historicalanalogsignal',
            name='color',
            field=models.CharField(default='#000000', help_text='The color of the signal in HEX', max_length=7),
        ),
    ]
