# Generated by Django 4.2.8 on 2025-04-29 13:24

import core.enums
from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_neuronmodel_collection_modelcollection_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalroi",
            name="label",
            field=models.CharField(
                blank=True, help_text="The label of the ROI", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalroi",
            name="max_t",
            field=models.IntegerField(
                default=0, help_text="The maximum time of the ROI"
            ),
        ),
        migrations.AddField(
            model_name="historicalroi",
            name="min_t",
            field=models.IntegerField(
                default=0, help_text="The minimum time of the ROI"
            ),
        ),
        migrations.AddField(
            model_name="roi",
            name="label",
            field=models.CharField(
                blank=True, help_text="The label of the ROI", max_length=1000, null=True
            ),
        ),
        migrations.AddField(
            model_name="roi",
            name="max_t",
            field=models.IntegerField(
                default=0, help_text="The maximum time of the ROI"
            ),
        ),
        migrations.AddField(
            model_name="roi",
            name="min_t",
            field=models.IntegerField(
                default=0, help_text="The minimum time of the ROI"
            ),
        ),
        migrations.AlterField(
            model_name="historicalroi",
            name="kind",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("line", "Line"), ("point", "Point"), ("spike", "Spike")],
                choices_enum=core.enums.RoiKindChoices,
                default="spike",
                help_text="The Roi can have vasrying kind, consult your API",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="roi",
            name="kind",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("line", "Line"), ("point", "Point"), ("spike", "Spike")],
                choices_enum=core.enums.RoiKindChoices,
                default="spike",
                help_text="The Roi can have vasrying kind, consult your API",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="simulations",
                to="core.neuronmodel",
            ),
        ),
    ]
