# Generated by Django 5.2 on 2025-09-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_analogsignal_color_analogsignalchannel_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analogsignalchannel',
            name='color',
            field=models.CharField(blank=True, help_text='The color of the signal in HEX', max_length=7, null=True),
        ),
    ]
