# Generated by Django 6.0.4 on 2026-04-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_mechanism_environment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mechanism',
            name='parameter_ports',
        ),
        migrations.AddField(
            model_name='mechanism',
            name='parameters',
            field=models.JSONField(default=list, help_text='The parameter ports of the mechanism, stored as a json object with the port name as key and the port type as value'),
        ),
    ]
