# Generated by Django 4.2.8 on 2025-05-01 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0008_historicalroi_label_historicalroi_max_t_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="simulation",
            name="creator",
            field=models.ForeignKey(
                help_text="The user that created the run",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
