# Generated by Django 5.2 on 2025-09-26 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_analogsignalchannel_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='analogsignal',
            name='time_trace',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='analog_signal_time_traces', to='core.trace'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalanalogsignal',
            name='time_trace',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.trace'),
        ),
    ]
