# Generated by Django 6.0.4 on 2026-06-16 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_mechanism_parameter_ports_and_more'),
        ('koherent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalanalogsignal',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalblock',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicaldataset',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalexperiment',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalinstrument',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalirregularlysampledsignal',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalroi',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalspiketrain',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicaltrace',
            name='assignation_id',
        ),
        migrations.RemoveField(
            model_name='historicalviewcollection',
            name='assignation_id',
        ),
        migrations.AddField(
            model_name='historicalanalogsignal',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalblock',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalexperiment',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalinstrument',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalirregularlysampledsignal',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalroi',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalspiketrain',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicaltrace',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
        migrations.AddField(
            model_name='historicalviewcollection',
            name='task',
            field=models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task'),
        ),
    ]
