# Generated by Django 4.2.8 on 2025-05-01 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_simulation_created_at_simulation_creator"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExperimentRecordingView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offset",
                    models.FloatField(
                        blank=True,
                        help_text="The offset of the view in seconds",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True,
                        help_text="The duration of the view in seconds",
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="The label of the view",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recording_views",
                        to="core.experiment",
                    ),
                ),
                (
                    "recording",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiment_views",
                        to="core.recording",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperimentStimulusView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offset",
                    models.FloatField(
                        blank=True,
                        help_text="The offset of the view in seconds",
                        null=True,
                    ),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True,
                        help_text="The duration of the view in seconds",
                        null=True,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="The label of the view",
                        max_length=1000,
                        null=True,
                    ),
                ),
                (
                    "experiment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stimulus_views",
                        to="core.experiment",
                    ),
                ),
                (
                    "stimulus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiment_views",
                        to="core.stimulus",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ExperimentView",
        ),
    ]
