# Generated by Django 5.2 on 2025-10-05 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0002_membership'),
        ('core', '0009_analogsignal_time_trace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='authentikate.organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalblock',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
    ]
