# Generated by Django 6.0.4 on 2026-06-16 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_create_empty_environment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuronmodel',
            name='environment',
            field=models.ForeignKey(help_text='The mod environment that the neuron model belongs to', on_delete=django.db.models.deletion.CASCADE, to='core.modenvironment'),
        ),
    ]
