# Generated by Django 6.0.4 on 2026-06-16 15:00

import kanne.fields
from django.db import migrations


# Largest value a Postgres ``bigint`` (the canonical QuantityField column) holds.
BIGINT_MAX = 9_223_372_036_854_775_807


# (model, field, factor) — factor converts the legacy float value (seconds / Hz)
# into the new canonical sub-unit integer (picoseconds for durations, nanohertz
# for the sampling rate).
CONVERSIONS = [
    ("AnalogSignal", "t_start", 1_000_000_000_000),
    ("AnalogSignal", "sampling_rate", 1_000_000_000),
    ("HistoricalAnalogSignal", "t_start", 1_000_000_000_000),
    ("HistoricalAnalogSignal", "sampling_rate", 1_000_000_000),
    ("ExperimentRecordingView", "offset", 1_000_000_000_000),
    ("ExperimentRecordingView", "duration", 1_000_000_000_000),
    ("ExperimentStimulusView", "offset", 1_000_000_000_000),
    ("ExperimentStimulusView", "duration", 1_000_000_000_000),
    ("Simulation", "dt", 1_000_000_000_000),
    ("Simulation", "duration", 1_000_000_000_000),
]


def _rescale(apps, *, to_canonical):
    """Multiply (forwards) or divide (backwards) legacy values by their factor.

    Runs while the columns are still FloatFields (forwards: before the
    AlterFields; backwards: after they have been reverted), so the arithmetic
    happens in float space and the AlterField casts the rounded result.
    """
    for model_name, field, factor in CONVERSIONS:
        Model = apps.get_model("core", model_name)
        for obj in Model.objects.exclude(**{f"{field}__isnull": True}):
            value = getattr(obj, field)
            if to_canonical:
                # Skip rows already stored in canonical sub-units: a genuine
                # legacy float (seconds / Hz) scales well within bigint, so a
                # product that overflows means the value was already converted
                # (e.g. by newer app code). Re-scaling it would double-convert
                # and overflow the bigint column.
                if abs(value) * factor > BIGINT_MAX:
                    continue
                new_value = round(value * factor)
            else:
                new_value = value / factor
            setattr(obj, field, new_value)
            obj.save(update_fields=[field])


def forwards(apps, schema_editor):
    _rescale(apps, to_canonical=True)


def backwards(apps, schema_editor):
    _rescale(apps, to_canonical=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_neuronmodel_environment'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
        # The RunPython above saves rows whose FK constraints are DEFERRABLE
        # INITIALLY DEFERRED, queuing deferred trigger events. The AlterField
        # operations below rewrite tables (e.g. core_simulation), which Postgres
        # forbids while trigger events are pending ("cannot ALTER TABLE ...
        # because it has pending trigger events"). Force the deferred triggers to
        # fire now so the table rewrites can proceed.
        migrations.RunSQL(
            "SET CONSTRAINTS ALL IMMEDIATE",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='blocksegment',
            name='end_time',
            field=kanne.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The end time of the segment, stored in picoseconds', null=True),
        ),
        migrations.AddField(
            model_name='blocksegment',
            name='start_time',
            field=kanne.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The start time of the segment, stored in picoseconds', null=True),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='sampling_rate',
            field=kanne.fields.QuantityField(base_unit='nanohertz', default=1000000000000, help_text='The sampling frequency of the signal, stored in nanohertz'),
        ),
        migrations.AlterField(
            model_name='analogsignal',
            name='t_start',
            field=kanne.fields.QuantityField(base_unit='picosecond', default=0, help_text='The start time of the signal, stored in picoseconds'),
        ),
        migrations.AlterField(
            model_name='experimentrecordingview',
            name='duration',
            field=kanne.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The duration of the view, stored in picoseconds', null=True),
        ),
        migrations.AlterField(
            model_name='experimentrecordingview',
            name='offset',
            field=kanne.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The offset of the view, stored in picoseconds', null=True),
        ),
        migrations.AlterField(
            model_name='experimentstimulusview',
            name='duration',
            field=kanne.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The duration of the view, stored in picoseconds', null=True),
        ),
        migrations.AlterField(
            model_name='experimentstimulusview',
            name='offset',
            field=kanne.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The offset of the view, stored in picoseconds', null=True),
        ),
        migrations.AlterField(
            model_name='historicalanalogsignal',
            name='sampling_rate',
            field=kanne.fields.QuantityField(base_unit='nanohertz', default=1000000000000, help_text='The sampling frequency of the signal, stored in nanohertz'),
        ),
        migrations.AlterField(
            model_name='historicalanalogsignal',
            name='t_start',
            field=kanne.fields.QuantityField(base_unit='picosecond', default=0, help_text='The start time of the signal, stored in picoseconds'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='dt',
            field=kanne.fields.QuantityField(base_unit='picosecond', default=1000000000000, help_text='The time step of the run, stored in picoseconds'),
        ),
        migrations.AlterField(
            model_name='simulation',
            name='duration',
            field=kanne.fields.QuantityField(base_unit='picosecond', help_text='The duration of the run, stored in picoseconds'),
        ),
    ]
