# Generated by Django 6.0.4 on 2026-06-17 19:21

import django.db.models.deletion
import kanne.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('core', '0013_enable_pg_trgm'),
        ('koherent', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBlockSegment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('start_time', kanne.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The start time of the segment, stored in picoseconds', null=True)),
                ('end_time', kanne.fields.QuantityField(base_unit='picosecond', blank=True, help_text='The end time of the segment, stored in picoseconds', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.blocksegment')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.block')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
            ],
            options={
                'verbose_name': 'historical block segment',
                'verbose_name_plural': 'historical block segments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNeuronModel',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, help_text='The hash of the model', max_length=1000)),
                ('json_model', models.JSONField(blank=True, default=dict, help_text='The json model of the neuron')),
                ('name', models.CharField(help_text='The name of the model', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentikate.client')),
                ('creator', models.ForeignKey(blank=True, db_constraint=False, help_text='The user that created the model', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('environment', models.ForeignKey(blank=True, db_constraint=False, help_text='The mod environment that the neuron model belongs to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.modenvironment')),
                ('history_relation', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='provenance_entries', to='core.neuronmodel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, db_constraint=False, help_text='The parent model of the neuron', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.neuronmodel')),
                ('task', models.ForeignKey(blank=True, help_text='The task during which the change occurred, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='koherent.task')),
            ],
            options={
                'verbose_name': 'historical neuron model',
                'verbose_name_plural': 'historical neuron models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
