# Generated by Django 6.0.4 on 2026-06-22 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_historicalblocksegment_historicalneuronmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalneuronmodel',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The parent model of the neuron (if it was derived from another model)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.neuronmodel'),
        ),
        migrations.AlterField(
            model_name='neuronmodel',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent model of the neuron (if it was derived from another model)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.neuronmodel'),
        ),
        migrations.CreateModel(
            name='ModelWorkspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the workspace', max_length=1000)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(help_text='The user that created the workspace', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pinned_by', models.ManyToManyField(help_text='The users that have pinned the workspace', related_name='pinned_workspaces', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkspaceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_group', models.CharField(help_text='The group of the workspace that the mapping belongs to (if its subdivided into groups)', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(help_text='The neuron model that the mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.neuronmodel')),
                ('workspace', models.ForeignKey(help_text='The workspace that the mapping belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.modelworkspace')),
            ],
        ),
    ]
