# Generated by Django 6.0.4 on 2026-06-24 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentikate', '0005_alter_client_client_id'),
        ('core', '0015_alter_historicalneuronmodel_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocksegment',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that owns the segment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_segments', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='experimentrecordingview',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that owns the recording view', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_recording_views', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='experimentstimulusview',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that owns the stimulus view', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiment_stimulus_views', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='file',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that owns the file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalblocksegment',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization that owns the segment', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='historicalviewcollection',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The organization that owns the view collection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='modelcollection',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that owns the model collection', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_collections', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='modelworkspace',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that owns the workspace', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='model_workspaces', to='authentikate.organization'),
        ),
        migrations.AddField(
            model_name='viewcollection',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The organization that owns the view collection', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='view_collections', to='authentikate.organization'),
        ),
    ]
