# Generated by Django 6.0.4 on 2026-09-18 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0002_datalayerstore_orphaned_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparseStore',
            fields=[
                ('datalayerstore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datalayer.datalayerstore')),
                ('spec', models.CharField(blank=True, help_text='The version of the `sporadik` block this store was accepted under. A spec selects how every byte in the prefix is read, so an unknown one is refused rather than guessed at', max_length=16, null=True)),
                ('shape', models.JSONField(blank=True, help_text='The shape of the matrix, as the root block declares it and every layout agrees. Two axes', null=True)),
                ('layouts', models.JSONField(blank=True, help_text='The stored layouts, one entry per `layouts/<encoding>` child: its path, `encoding`, `encoding-version`, `nnz`, `dtype` and the chunk length of each of `data`, `indices` and `indptr`. Everything that differs between layouts, and nothing that does not. The chunking is here because it decides the read cost: `indptr` names exactly which bytes a lookup wants and a chunk is the granularity at which they can be fetched, so the two have to agree -- measured on a 16 um matrix, one slice costs 0.95 ms at 32 768-element chunks and 23.55 ms at 4 Mi ones, the same bytes a hundred times over-read', null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('datalayer.datalayerstore',),
        ),
        migrations.AddField(
            model_name='parquetstore',
            name='columns',
            field=models.JSONField(blank=True, help_text="The file's own schema, as DESCRIBE reports it: one entry per column with `name`, `type` and `nullable`, in file order. Read off the parquet when the upload was finished, never declared -- a fact derived from the artifact cannot be declared wrong, which is what a column's dtype used to be. Null only for a store written before this field existed, or one whose bytes could not be described.", null=True),
        ),
    ]
