# Generated by Django 6.0.4 on 2026-09-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayer', '0004_zarrstore_shards_alter_zarrstore_chunks'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayerstore',
            name='size_bytes',
            field=models.BigIntegerField(blank=True, help_text='How many bytes this store actually holds, measured when the upload was finished. Null while an upload is unfinished, or for stores written before this was recorded', null=True),
        ),
    ]
